### ISSUE TITLE
Payment protocol support

### ISSUE THREAD

**Issue by luke-jr** [ElementsProject/elementsproject.org#5]
What is the current status of payment protocol? We should make it work.

**Comment by sipa** [comment]
My guess: it will work fine, but won't do CT, as there is no way to
communicate blinding keys.

**Comment by martindale** [comment]
I believe this issue should be re-created in `ElementsProject/elements`.  Anyone have thoughts otherwise?

**Comment by sipa** [comment]
Yes, agree.

**Comment by martindale** [comment]
Closing here.
