### ISSUE TITLE
Broken link on bitmasksighash page

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/elementsproject.org#56]
https://www.elementsproject.org/elements/bitmask-sighash-modes/

https://github.com/ElementsProject/elementsproject.org/edit/master/source/elements/bitmask-sighash-modes/index.md

Has a link to: https://github.com/ElementsProject/elements/tree/feature_bitmasksighash

Which is not found.

**Comment by wintercooled** [comment]
Closing - relates to now redundant site

**Comment by maaku** [comment]
Redundant? What’s the new site?

**Comment by wintercooled** [comment]
This issue was raised against this repo in March and the last merge was December 2017 so it seemed prudent to close it as unresolved.

**Comment by maaku** [comment]
Ok. Your message “relates to now redundant site” makes it sound like there is some other official site instead, so I was confused.
